version: "3.8"
services:
  db:
    container_name: postgresql-op-frames
    image: postgres:16-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  db:
    driver: local
